export default [
    {
      id: 1,
      title: 'Samsung Galaxy S7',
      price: 599.99,
      img: 'https://www.course-api.com/images/cart/phone-1.png',
      amount: 1,
    },
    {
      id: 2,
      title: 'google pixel ',
      price: 499.99,
      img: 'https://www.course-api.com/images/cart/phone-2.png',
      amount: 1,
    },
    {
      id: 3,
      title: 'Xiaomi Redmi Note 2',
      price: 699.99,
      img: 'https://www.course-api.com/images/cart/phone-3.png',
      amount: 1,
    },
    {
        id: 4,
        title: 'Samsung Galaxy S7',
        price: 599.99,
        img: 'https://www.course-api.com/images/cart/phone-4.png',
        amount: 1,
      },
      {
        id: 5,
        title: 'google pixel ',
        price: 499.99,
        img: 'https://www.course-api.com/images/cart/phone-2.png',
        amount: 1,
      },
      {
        id: 6,
        title: 'Xiaomi Redmi Note 2',
        price: 699.99,
        img: 'https://www.course-api.com/images/cart/phone-3.png',
        amount: 1,
      },
      {
        id: 7,
        title: 'Samsung Galaxy S7',
        price: 599.99,
        img: 'https://www.course-api.com/images/cart/phone-1.png',
        amount: 1,
      },
      {
        id: 8,
        title: 'google pixel ',
        price: 499.99,
        img: 'https://www.course-api.com/images/cart/phone-2.png',
        amount: 1,
      },
      {
        id: 9,
        title: 'Xiaomi Redmi Note 2',
        price: 699.99,
        img: 'https://www.course-api.com/images/cart/phone-3.png',
        amount: 1,
      },
      {
          id: 10,
          title: 'Samsung Galaxy S7',
          price: 599.99,
          img: 'https://www.course-api.com/images/cart/phone-4.png',
          amount: 1,
        },
  ];
  